name: AI Code Review
on: [ pull_request ]

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extrair diff do PR
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          echo "Comparing against branch: $BASE"
          git fetch origin "$BASE"
          git diff origin/"$BASE"...HEAD > pr.diff

      - name: Chamar OpenAI Chat Completions
        id: call_openai
        run: |
          cat <<EOF > payload.json
          {
            "model": "gpt-3.5-turbo",
            "temperature": 0.2,
            "max_tokens": 1024,
            "messages": [
              { "role": "system", "content": "Você é um revisor de código experiente." },
              { "role": "user",   "content": "Analise o diff abaixo e comente bugs, violações de estilo e sugestões:\n\`\`\`\n$(sed 's/"/\\"/g' pr.diff)\n\`\`\`" }
            ]
          }
          EOF

          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            --data @payload.json)

          COMMENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          echo "comments<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT"    >> $GITHUB_OUTPUT
          echo "EOF"         >> $GITHUB_OUTPUT

      - name: Publicar comentários no PR
        run: |
          gh pr review ${{ github.event.pull_request.number }} \
            --comment "${{ steps.call_openai.outputs.comments }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
